#!/usr/local/bin/bash -u

paramdir="./data/test_eta_sigma_s/param"
for eta in $(seq -w 0.5 0.1 0.7); do
    for sigma in $(seq -w 0 1 10); do
        for s in $(seq -w 0 20 120); do
            param=$paramdir/eta_$eta\sigma_0.0$sigma\s_$s
            [ -e $param ] &&  ./bin/run $param &
        done
        wait
    done
    wait
done
