#!/usr/local/bin/bash -u

paramdir="./data/test_eta_small_sigma_2/param"
for eta in $(seq -w 0.3 0.1 1.0); do
    for sigma in $(seq -w 0 1 12); do
            param=$paramdir/eta_$eta"sigma_0.0"$sigma
            [ -e $param ] &&  ./bin/run $param &
    done
    wait
done
