#!/usr/local/bin/bash -u

step=10
paramdir="./data/test_eta_small_sigma/param/"
for eta in $(seq -w 0.1 0.1 1.0); do
    for sigma in $(seq -w 0 1 40); do
            param=$paramdir/eta_$eta"sigma_0.0"$sigma
            [ -e $param ] && ./bin/run $param &
    done
    wait
done
