#!/usr/local/bin/zsh -u

dir=../data/soturon/param

eta=1
sigma=0
s=(1 5 10 50 100 5000)

width=100
ps=0.7

for i in $s; do
    ../bin/plot_pdf -pdf -width $width -ps $ps $dir/param2_eta$eta\_sigma$sigma\_s$i | gnuplot -p
done
