#!/usr/local/bin/zsh -u

dir=../data/soturon/param

eta=(0.0 0.5 1 2 3 4)
s=1
sigma=0

width=500

for i in $eta; do
    ../bin/plot_pdf -pdf -width $width -ps 0.3 $dir/param1_eta$i\_sigma$sigma\_s$s | gnuplot -p
done
